# Generated by Django 4.1.2 on 2022-10-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Not', 'Not Urgent'), ('Soon', 'Due Soon'), ('Over', 'Overdue'), ('Complete', 'Completed')], default='Not', max_length=75)),
            ],
        ),
    ]
